// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID          pgtype.UUID
	Name        string
	MuscleGroup pgtype.Text
	Equipment   pgtype.Text
}

type ExerciseSet struct {
	ID         pgtype.UUID
	SessionID  pgtype.UUID
	ExerciseID pgtype.UUID
	SetNumber  int32
	WeightKg   float64
	Reps       int32
	Failure    pgtype.Bool
	LoggedAt   pgtype.Timestamptz
}

type Program struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	TotalWeeks  pgtype.Int4
	CreatedAt   pgtype.Timestamptz
}

type ProgramDay struct {
	ID         pgtype.UUID
	ProgramID  pgtype.UUID
	WeekNumber int32
	DayNumber  int32
	Label      string
}

type ProgramExercise struct {
	ID              pgtype.UUID
	ProgramDayID    pgtype.UUID
	ExerciseID      pgtype.UUID
	Position        int32
	Sets            int32
	RepMin          int32
	RepMax          int32
	WeightIncrement pgtype.Float8
}

type Session struct {
	ID           pgtype.UUID
	ProgramDayID pgtype.UUID
	WeekNumber   int32
	StartedAt    pgtype.Timestamptz
	EndedAt      pgtype.Timestamptz
	Notes        pgtype.Text
}
