// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  program_day_id,
  week_number,
  started_at,
  ended_at,
  notes
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, program_day_id, week_number, started_at, ended_at, notes
`

type CreateSessionParams struct {
	ProgramDayID pgtype.UUID
	WeekNumber   int32
	StartedAt    pgtype.Timestamptz
	EndedAt      pgtype.Timestamptz
	Notes        pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ProgramDayID,
		arg.WeekNumber,
		arg.StartedAt,
		arg.EndedAt,
		arg.Notes,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.WeekNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.Notes,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, program_day_id, week_number, started_at, ended_at, notes FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.WeekNumber,
		&i.StartedAt,
		&i.EndedAt,
		&i.Notes,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, program_day_id, week_number, started_at, ended_at, notes FROM sessions
ORDER BY started_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.WeekNumber,
			&i.StartedAt,
			&i.EndedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
